version: "3"

services:
  master:
    build:
      context: master
      dockerfile: Dockerfile
    environment:
      - "REDIS_URL=${REDIS_URL}"
      - "REDIS_PORT=${REDIS_PORT}"
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"

  #   # For simulated version
  #   depends_on:
  #     - robot
  # robot:
  #   build:
  #     context: robot
  #     dockerfile: Dockerfile
  #   environment:
  #     - "REDIS_URL=${REDIS_URL}"
  #     - "REDIS_PORT=${REDIS_PORT}"
  #     - "PERCEPT_CHANNEL=${PERCEPT_CHANNEL}"
  #     - "COMMAND_CHANNEL=${COMMAND_CHANNEL}"
  #   depends_on:
  #     - redis
  # redis:
  #   image: "redis"
  #   environment:
  #     - ALLOW_EMPTY_PASSWORD=yes
