version: "3"

services:
  master:
    build:
      context: master
      dockerfile: Dockerfile
    environment:
      - "REDIS_URL=${REDIS_URL}"
      - "REDIS_PORT=${REDIS_PORT}"
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    depends_on:
      - robot
  robot:
    build:
      context: robot
      dockerfile: Dockerfile
    environment:
      - "REDIS_URL=${REDIS_URL}"
      - "REDIS_PORT=${REDIS_PORT}"
    depends_on:
      - redis
  redis:
    image: "redis"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
