version: "3"

services:
  ros1:
    build:
      context: ./
      dockerfile: ros1.Dockerfile
    ports:
      - "11311:11311/tcp"
    networks:
      - my_network

  ros2:
    build:
      context: ./
      dockerfile: ros2-2.Dockerfile
    networks:
      - my_network
    environment:
      - "ROS_HOSTNAME=bridge"
      - "ROS_MASTER_URI=http://ros1:11311"
    volumes:
      - ./src/ros_tutorials:/root/src

  bridge:
    image: ros:foxy-ros1-bridge
    environment:
      - "ROS_HOSTNAME=bridge"
      - "ROS_MASTER_URI=http://ros1:11311"
    networks:
      - my_network
    command: ros2 run ros1_bridge dynamic_bridge

networks:
  my_network:
    driver: bridge
